####################################################################################################
#                                                                                                  #
#                    █▀▄▀█ █░█ █░░ ▀█▀ █ █░█ █▀▀ █▀█ █▀ █▀▀   █▀▀ █▀█ █▀█ █▀▀                      #
#                    █░▀░█ █▄█ █▄▄ ░█░ █ ▀▄▀ ██▄ █▀▄ ▄█ ██▄   █▄▄ █▄█ █▀▄ ██▄                      #
#                                                                                                  #
#                                                                                                  #
#    WIKI:        https://github.com/Multiverse/Multiverse-Core/wiki                               #
#    DISCORD:     https://discord.gg/NZtfKky                                                       #
#    BUG REPORTS: https://github.com/Multiverse/Multiverse-Core/issues                             #
#                                                                                                  #
#                                                                                                  #
#    Each option in this file is documented and explained here:                                    #
#     ==>  https://github.com/Multiverse/Multiverse-Core/wiki/config.yml                           #
#                                                                                                  #
#                                                                                                  #
#    New options are added to this file automatically. If you manually made changes                #
#    to this file while your server is running, please run `/mv reload` command.                   #
#                                                                                                  #
####################################################################################################
  
  
world:
  # When enabled, Multiverse will automatically import default worlds defined in the server.properties
  # `level-name` property when the Multiverse is enabled or reloaded. This will include the nether and 
  # end if the server created them.
  auto-import-default-worlds: true
  
  # When enabled, Multiverse will import all other worlds created by other plugins when Multiverse starts
  # or when Multiverse is reloaded.
  auto-import-3rd-party-worlds: true

  # This setting will prevent players from entering worlds they don't have access to.
  # If this is set to false, players will be able to enter any world they want.
  # If this is set to true, players will only be able to enter worlds they have
  # the `mv.access.<worldname>` permission.
  enforce-access: false
  
  # Sets whether Multiverse will should enforce gamemode on world change.
  # If enabled, players will be forced into the gamemode of the world they are entering, unless they have
  # the `mv.bypass.gamemode.<worldname>` permission.
  enforce-gamemode: true
  
  # Sets whether Multiverse will should globally enforce flight ability on worlds.
  # Disable this if you want another plugin to handle player's flight ability.
  # Disabling this will make the world property `allow-flight` have no effect.
  enforce-flight: true
  
  # Sets whether Multiverse will purge entities on world load based world's entity spawn config.
  auto-purge-entities: false
  
  # Format for world names for multiverse to automatically detect a world group consist of overworld, nether and end.
  # This is used default-respawn-in-overworld and potentially other features.
  world-name-format:
    nether: '%overworld%_nether'
    end: '%overworld%_the_end'
  
  
teleport:
  # Sets whether Multiverse will use more fine-grained teleport permissions.
  # ----
  # New finer teleport permissions for /mvtp and /mvspawn commands:
  #   - For specific teleport types: `multiverse.teleport.<self|other>.<type>.<target>`
  #   - For specific world spawn: `multiverse.core.spawn.<self|other>.<worldname>`
  # For example, if `multiverse.teleport.self.w.world2` is set, Multiverse will only allow the player to teleport to the world2.
  # ----
  # Legacy permissions will be used if this is set to false:
  #   - For teleport destinations: `multiverse.teleport.<self|other>.<type>`
  #   - For spawn: `multiverse.core.spawn.<self|other>`
  use-finer-teleport-permissions: true
  
  # Sets the maximum number of players allowed to be teleported at once with `/mv teleport` command
  concurrent-teleport-limit: 50
  
  # If this is set to true, Multiverse will enforce access permissions for all teleportation,
  # including teleportation from other plugins. You should not disable this unless you are facing
  # conflict with another plugin handling teleportation.
  teleport-intercept: true
  
  # Sets the horizontal (x and z-axis) search radius for finding a safe location to teleport to.
  # Increasing this value will widen the search area at the cost of performance.
  # To disable, set to 0.
  safe-location-horizontal-search-radius: 3
  
  # Sets the vertical (y-axis) search radius for finding a safe location to teleport to.
  # Increasing this value will widen the search area at the cost of performance.
  # To disable, set to 0.
  safe-location-vertical-search-radius: 3
  
  
spawn:
  # Sets whether Multiverse will override the first spawn location of a world.
  # If enabled, Multiverse will set the first spawn location of a world to the spawn location of the world.
  # If disabled, it will default to server.properties settings.
  first-spawn-override: false
  
  # Sets the world that Multiverse will use as the location for players that first join the server.
  # This only applies if first-spawn-override is set to true.
  first-spawn-location: ''
  
  # Enables join-destination below.
  enable-join-destination: false
  
  # Sets the destination that Multiverse will use to spawn players on every login
  # Set the above enable-join-destination to false to disable
  join-destination: ''
  
  # This only applies if the `respawn-world` property is not set for the world that the player died in,
  # and the player does not have bed or anchor set.
  # ----
  # When this option is enabled, players will respawn in the overworld when dying in nether or end, mimicking the vanilla behavior.
  # The automatic selection of overworld is determined by the `world-name-format` config section above.
  # This option takes precedence over the `default-respawn-within-same-world` option.
  # ----
  # Set this to false if you want another plugin to handle respawning or do not want this vanilla behavior.
  default-respawn-in-overworld: true
  
  # This only applies if the `respawn-world` property is not set for the world that the player died in,
  # and the player does not have bed or anchor set.
  # ----
  # When this option is enabled, players will respawn in the same world's that they died in.
  # If the /spawnpoint is already within that world and `enforce-respawn-at-world-spawn` is disabled,
  # Multiverse will use that spawn location, else it will use the world's spawn where the player died in.
  # ----
  # You can set `respawn-world` property with the command: `/mv modify <worldname> set respawn-world <worldname>`
  # You can reset `respawn-world` property with the command: `/mv modify <worldname> reset respawn-world`
  # ----
  # Set this to false if you want another plugin to handle respawning.
  default-respawn-within-same-world: true
  
  # When this option is enabled, players will always respawn at the world's spawn location of calculated respawn world,
  # unless bed or anchor is set and `bed-respawn` or `anchor-spawn` is enabled respectively.
  # ----
  # Set this to false if you want to use a custom spawn location such as /spawnpoint instead of the world's spawn location.
  enforce-respawn-at-world-spawn: true
  
  
portal:
  # This config option defines whether or not Multiverse should interfere with's Bukkit's default portal search radius.
  # Setting it to false would mean you want to simply let Bukkit decides the search radius itself.
  use-custom-portal-search: false
  
  # This config option defines the search radius Multiverse should use when searching for a portal.
  # This only applies if use-custom-portal-search is set to true.
  custom-portal-search-radius: 128
  
  
messaging:
  # This config option defines whether or not Multiverse should prefix the chat with the world name.
  # This only applies if use-custom-portal-search is set to true.
  enable-chat-prefix: true
  
  # This config option defines the format Multiverse should use when prefixing the chat with the world name.
  # This only applies if enable-chat-prefix is set to true.
  chat-prefix-format: '&cW &r[%world%] %chat%'
  
  # This config option defines whether or not Multiverse should register the PlaceholderAPI hook.
  # This only applies if PlaceholderAPI is installed.
  register-papi-hook: true
  
  # This config option defines the default language Multiverse should use.
  default-locale: en
  
  # This config option defines if Multiverse should use the player's language based on their client's language.
  # If the player's language does not have a translation, it will use the default language set above instead.
  per-player-locale: true
  
  
command:
  # If this is set to true, Multiverse will resolve world based on their alias names for commands and destinations.
  # Normal world names will still be accepted.
  # In the event you have multiple worlds with the same alias name, the first world found will be used.
  resolve-alias-name: true
  
  # This config option defines whether `/mv confirm` is needed before running a DANGEROUS action.
  #   enable: `/mv confirm` is required.
  #   player_only: `/mv confirm` only required when running command as a player.
  #   disable_command_blocks: `/mv confirm` not required for command blocks.
  #   disable_console: `/mv confirm` not required for the console.
  #   disable: `/mv confirm` is not required.
  confirm-mode: enable
  
  # If this is set to true, `/mv confirm` will include a 3 digit random number that must be entered to confirm the command.
  # For example: `/mv confirm 726`
  use-confirm-otp: true
  
  # The amount of time in seconds before `/mv confirm` times out
  confirm-timeout: 30
  
  # If this is set to true, legacy aliases will be shown in tab completion.
  # These are old mv4 aliases such as `/mvclone` in addition to `/mv clone` which crowds the tab completion.
  # !!!NOTE: This will only apply after a server restart!
  show-legacy-aliases: false
  
  
event-priority:
  # The follow configuration changes the bukkit's EventPriority for certain events.
  # Only ever change this if you need multiverse's events outcomes to override another plugin, or if
  # you want another plugin's outcome to override multiverse's.
  # ----
  # !!!NOTE: This will only apply after a server restart!
  
  # This config option defines the priority for the PlayerPortalEvent.
  player-portal: high
  
  # This config option defines the priority for the PlayerRespawnEvent.
  player-respawn: low
  
  # This config option defines the priority for the PlayerSpawnLocationEvent.
  player-spawn-location: normal
  
  # This config option defines the priority for the PlayerTeleportEvent.
  player-teleport: highest
  
  
misc:
  # Change this if you use a custom path for the bukkit.yml file with `--bukkit-settings` startup flag.
  # Note: this config option needs a server restart to take effect.
  bukkit-yml-path: config/bukkit.yml
  
  # This is our debug flag to help identify issues with Multiverse.
  # If you are having issues with Multiverse, please set this to 3 and then post your log to pastebin.com
  # Otherwise, there's no need to touch this. If not instructed by a wiki page or developer.
  #   0 = Off, No debug messages
  #   1 = fine
  #   2 = finer
  #   3 = finest
  global-debug: 2
  # Sets whether console will log every permission check done by all multiverse plugins.
  # This will only work if the above 'global-debug' is set to 1 or more.
  debug-permissions: false
  
  # If true, the startup console messages will no longer show.
  silent-start: false
  
  # If you don't want to donate, you can set this to false and Multiverse will stop nagging you.
  show-donation-message: true
  
  
# This just signifies the version number so we can see what version of config you have.
# NEVER TOUCH THIS VALUE
version: 5.2
