name: Build and Deploy to Pages

on:
  push:
    branches: ['main']

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'npm'

      - run: npm install

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: 'sveltekit'

      - run: npm run build
        id: build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
